version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-inventory}
    ports:
      - "5435:5432" # Maps port 5435 on host to 5432 in database container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-inventory}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sharmatanikesh/inventory-backend:latest
    container_name: inventory_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENV=${ENV:-dev}
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-inventory}?sslmode=disable
    ports:
      - "8000:8000"
    command: sh -c "python -m app.database.database --init-db && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    networks:
      - app-network
  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend:8000
    image: sharmatanikesh/inventory-frontend:latest
    container_name: inventory_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - BACKEND_API_URL=http://backend:8000
      - PORT=5173
    ports:
      - "5173:5173"
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
